import { Gun, GunType } from '../types';

export const GUNS: Record<GunType, Gun> = {
  blaster: {
    type: 'blaster',
    name: 'Blaster',
    damage: 1,
    fireRate: 200,
    projectileSpeed: 10,
    projectileColor: '#ffaa00',
    spread: 0,
    projectilesPerShot: 1,
  },
  shotgun: {
    type: 'shotgun',
    name: 'Shotgun',
    damage: 1,
    fireRate: 600,
    projectileSpeed: 12,
    projectileColor: '#ff4400',
    spread: 0.3,
    projectilesPerShot: 5,
  },
  railgun: {
    type: 'railgun',
    name: 'Railgun',
    damage: 3,
    fireRate: 1200,
    projectileSpeed: 25,
    projectileColor: '#00aaff',
    spread: 0,
    projectilesPerShot: 1,
  },
  plasma: {
    type: 'plasma',
    name: 'Plasma Gun',
    damage: 1,
    fireRate: 100,
    projectileSpeed: 8,
    projectileColor: '#00ccff',
    spread: 0.1,
    projectilesPerShot: 1,
  },
  rocket: {
    type: 'rocket',
    name: 'Rocket Launcher',
    damage: 5,
    fireRate: 800,
    projectileSpeed: 7,
    projectileColor: '#ff6600',
    spread: 0,
    projectilesPerShot: 1,
  },
  lightning: {
    type: 'lightning',
    name: 'Lightning Gun',
    damage: 1,
    fireRate: 80,
    projectileSpeed: 20,
    projectileColor: '#cc00ff',
    spread: 0.05,
    projectilesPerShot: 1,
  },
};
